// auto-generated by tools/kr_gen.py — 한글 반쪽 글리프 테이블 (음절*2 + 0/1 = 좌/우)
ALIGNED8 static const Texture kr_g_AC00_L[] = {
#include "textures/segment2/kr/kr_AC00_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC00_R[] = {
#include "textures/segment2/kr/kr_AC00_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC01_L[] = {
#include "textures/segment2/kr/kr_AC01_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC01_R[] = {
#include "textures/segment2/kr/kr_AC01_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC04_L[] = {
#include "textures/segment2/kr/kr_AC04_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC04_R[] = {
#include "textures/segment2/kr/kr_AC04_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC07_L[] = {
#include "textures/segment2/kr/kr_AC07_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC07_R[] = {
#include "textures/segment2/kr/kr_AC07_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC15_L[] = {
#include "textures/segment2/kr/kr_AC15_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC15_R[] = {
#include "textures/segment2/kr/kr_AC15_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC1C_L[] = {
#include "textures/segment2/kr/kr_AC1C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC1C_R[] = {
#include "textures/segment2/kr/kr_AC1C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC70_L[] = {
#include "textures/segment2/kr/kr_AC70_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC70_R[] = {
#include "textures/segment2/kr/kr_AC70_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC74_L[] = {
#include "textures/segment2/kr/kr_AC74_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC74_R[] = {
#include "textures/segment2/kr/kr_AC74_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC78_L[] = {
#include "textures/segment2/kr/kr_AC78_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC78_R[] = {
#include "textures/segment2/kr/kr_AC78_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC8C_L[] = {
#include "textures/segment2/kr/kr_AC8C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AC8C_R[] = {
#include "textures/segment2/kr/kr_AC8C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACA0_L[] = {
#include "textures/segment2/kr/kr_ACA0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACA0_R[] = {
#include "textures/segment2/kr/kr_ACA0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACA8_L[] = {
#include "textures/segment2/kr/kr_ACA8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACA8_R[] = {
#include "textures/segment2/kr/kr_ACA8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACA9_L[] = {
#include "textures/segment2/kr/kr_ACA9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACA9_R[] = {
#include "textures/segment2/kr/kr_ACA9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACB0_L[] = {
#include "textures/segment2/kr/kr_ACB0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACB0_R[] = {
#include "textures/segment2/kr/kr_ACB0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACBC_L[] = {
#include "textures/segment2/kr/kr_ACBC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACBC_R[] = {
#include "textures/segment2/kr/kr_ACBC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACBD_L[] = {
#include "textures/segment2/kr/kr_ACBD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACBD_R[] = {
#include "textures/segment2/kr/kr_ACBD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACC4_L[] = {
#include "textures/segment2/kr/kr_ACC4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACC4_R[] = {
#include "textures/segment2/kr/kr_ACC4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACE0_L[] = {
#include "textures/segment2/kr/kr_ACE0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACE0_R[] = {
#include "textures/segment2/kr/kr_ACE0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACF3_L[] = {
#include "textures/segment2/kr/kr_ACF3_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACF3_R[] = {
#include "textures/segment2/kr/kr_ACF3_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACF5_L[] = {
#include "textures/segment2/kr/kr_ACF5_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACF5_R[] = {
#include "textures/segment2/kr/kr_ACF5_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACFC_L[] = {
#include "textures/segment2/kr/kr_ACFC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ACFC_R[] = {
#include "textures/segment2/kr/kr_ACFC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD00_L[] = {
#include "textures/segment2/kr/kr_AD00_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD00_R[] = {
#include "textures/segment2/kr/kr_AD00_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD11_L[] = {
#include "textures/segment2/kr/kr_AD11_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD11_R[] = {
#include "textures/segment2/kr/kr_AD11_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD34_L[] = {
#include "textures/segment2/kr/kr_AD34_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD34_R[] = {
#include "textures/segment2/kr/kr_AD34_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD6C_L[] = {
#include "textures/segment2/kr/kr_AD6C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD6C_R[] = {
#include "textures/segment2/kr/kr_AD6C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD70_L[] = {
#include "textures/segment2/kr/kr_AD70_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD70_R[] = {
#include "textures/segment2/kr/kr_AD70_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD74_L[] = {
#include "textures/segment2/kr/kr_AD74_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AD74_R[] = {
#include "textures/segment2/kr/kr_AD74_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ADC4_L[] = {
#include "textures/segment2/kr/kr_ADC4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ADC4_R[] = {
#include "textures/segment2/kr/kr_ADC4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ADF8_L[] = {
#include "textures/segment2/kr/kr_ADF8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ADF8_R[] = {
#include "textures/segment2/kr/kr_ADF8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ADFC_L[] = {
#include "textures/segment2/kr/kr_ADFC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_ADFC_R[] = {
#include "textures/segment2/kr/kr_ADFC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE00_L[] = {
#include "textures/segment2/kr/kr_AE00_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE00_R[] = {
#include "textures/segment2/kr/kr_AE00_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE09_L[] = {
#include "textures/segment2/kr/kr_AE09_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE09_R[] = {
#include "textures/segment2/kr/kr_AE09_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE30_L[] = {
#include "textures/segment2/kr/kr_AE30_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE30_R[] = {
#include "textures/segment2/kr/kr_AE30_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE34_L[] = {
#include "textures/segment2/kr/kr_AE34_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE34_R[] = {
#include "textures/segment2/kr/kr_AE34_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE38_L[] = {
#include "textures/segment2/kr/kr_AE38_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE38_R[] = {
#include "textures/segment2/kr/kr_AE38_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE4A_L[] = {
#include "textures/segment2/kr/kr_AE4A_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE4A_R[] = {
#include "textures/segment2/kr/kr_AE4A_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE4C_L[] = {
#include "textures/segment2/kr/kr_AE4C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE4C_R[] = {
#include "textures/segment2/kr/kr_AE4C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE4D_L[] = {
#include "textures/segment2/kr/kr_AE4D_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AE4D_R[] = {
#include "textures/segment2/kr/kr_AE4D_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AECD_L[] = {
#include "textures/segment2/kr/kr_AECD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AECD_R[] = {
#include "textures/segment2/kr/kr_AECD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AED8_L[] = {
#include "textures/segment2/kr/kr_AED8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AED8_R[] = {
#include "textures/segment2/kr/kr_AED8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AF2D_L[] = {
#include "textures/segment2/kr/kr_AF2D_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AF2D_R[] = {
#include "textures/segment2/kr/kr_AF2D_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AF41_L[] = {
#include "textures/segment2/kr/kr_AF41_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AF41_R[] = {
#include "textures/segment2/kr/kr_AF41_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AF64_L[] = {
#include "textures/segment2/kr/kr_AF64_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AF64_R[] = {
#include "textures/segment2/kr/kr_AF64_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AFC8_L[] = {
#include "textures/segment2/kr/kr_AFC8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_AFC8_R[] = {
#include "textures/segment2/kr/kr_AFC8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B044_L[] = {
#include "textures/segment2/kr/kr_B044_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B044_R[] = {
#include "textures/segment2/kr/kr_B044_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B053_L[] = {
#include "textures/segment2/kr/kr_B053_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B053_R[] = {
#include "textures/segment2/kr/kr_B053_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B054_L[] = {
#include "textures/segment2/kr/kr_B054_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B054_R[] = {
#include "textures/segment2/kr/kr_B054_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B05D_L[] = {
#include "textures/segment2/kr/kr_B05D_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B05D_R[] = {
#include "textures/segment2/kr/kr_B05D_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B07C_L[] = {
#include "textures/segment2/kr/kr_B07C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B07C_R[] = {
#include "textures/segment2/kr/kr_B07C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B098_L[] = {
#include "textures/segment2/kr/kr_B098_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B098_R[] = {
#include "textures/segment2/kr/kr_B098_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B099_L[] = {
#include "textures/segment2/kr/kr_B099_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B099_R[] = {
#include "textures/segment2/kr/kr_B099_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B0A0_L[] = {
#include "textures/segment2/kr/kr_B0A0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B0A0_R[] = {
#include "textures/segment2/kr/kr_B0A0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B0A9_L[] = {
#include "textures/segment2/kr/kr_B0A9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B0A9_R[] = {
#include "textures/segment2/kr/kr_B0A9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B0B4_L[] = {
#include "textures/segment2/kr/kr_B0B4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B0B4_R[] = {
#include "textures/segment2/kr/kr_B0B4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B0C9_L[] = {
#include "textures/segment2/kr/kr_B0C9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B0C9_R[] = {
#include "textures/segment2/kr/kr_B0C9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B0E5_L[] = {
#include "textures/segment2/kr/kr_B0E5_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B0E5_R[] = {
#include "textures/segment2/kr/kr_B0E5_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B108_L[] = {
#include "textures/segment2/kr/kr_B108_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B108_R[] = {
#include "textures/segment2/kr/kr_B108_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B10C_L[] = {
#include "textures/segment2/kr/kr_B10C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B10C_R[] = {
#include "textures/segment2/kr/kr_B10C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B110_L[] = {
#include "textures/segment2/kr/kr_B110_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B110_R[] = {
#include "textures/segment2/kr/kr_B110_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B118_L[] = {
#include "textures/segment2/kr/kr_B118_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B118_R[] = {
#include "textures/segment2/kr/kr_B118_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B124_L[] = {
#include "textures/segment2/kr/kr_B124_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B124_R[] = {
#include "textures/segment2/kr/kr_B124_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B140_L[] = {
#include "textures/segment2/kr/kr_B140_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B140_R[] = {
#include "textures/segment2/kr/kr_B140_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B178_L[] = {
#include "textures/segment2/kr/kr_B178_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B178_R[] = {
#include "textures/segment2/kr/kr_B178_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B180_L[] = {
#include "textures/segment2/kr/kr_B180_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B180_R[] = {
#include "textures/segment2/kr/kr_B180_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B192_L[] = {
#include "textures/segment2/kr/kr_B192_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B192_R[] = {
#include "textures/segment2/kr/kr_B192_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B204_L[] = {
#include "textures/segment2/kr/kr_B204_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B204_R[] = {
#include "textures/segment2/kr/kr_B204_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B208_L[] = {
#include "textures/segment2/kr/kr_B208_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B208_R[] = {
#include "textures/segment2/kr/kr_B208_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B20C_L[] = {
#include "textures/segment2/kr/kr_B20C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B20C_R[] = {
#include "textures/segment2/kr/kr_B20C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B294_L[] = {
#include "textures/segment2/kr/kr_B294_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B294_R[] = {
#include "textures/segment2/kr/kr_B294_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B298_L[] = {
#include "textures/segment2/kr/kr_B298_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B298_R[] = {
#include "textures/segment2/kr/kr_B298_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2C8_L[] = {
#include "textures/segment2/kr/kr_B2C8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2C8_R[] = {
#include "textures/segment2/kr/kr_B2C8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2D8_L[] = {
#include "textures/segment2/kr/kr_B2D8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2D8_R[] = {
#include "textures/segment2/kr/kr_B2D8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2E4_L[] = {
#include "textures/segment2/kr/kr_B2E4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2E4_R[] = {
#include "textures/segment2/kr/kr_B2E4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2E8_L[] = {
#include "textures/segment2/kr/kr_B2E8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2E8_R[] = {
#include "textures/segment2/kr/kr_B2E8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2EC_L[] = {
#include "textures/segment2/kr/kr_B2EC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2EC_R[] = {
#include "textures/segment2/kr/kr_B2EC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2F5_L[] = {
#include "textures/segment2/kr/kr_B2F5_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2F5_R[] = {
#include "textures/segment2/kr/kr_B2F5_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2F9_L[] = {
#include "textures/segment2/kr/kr_B2F9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B2F9_R[] = {
#include "textures/segment2/kr/kr_B2F9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B300_L[] = {
#include "textures/segment2/kr/kr_B300_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B300_R[] = {
#include "textures/segment2/kr/kr_B300_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B354_L[] = {
#include "textures/segment2/kr/kr_B354_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B354_R[] = {
#include "textures/segment2/kr/kr_B354_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B355_L[] = {
#include "textures/segment2/kr/kr_B355_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B355_R[] = {
#include "textures/segment2/kr/kr_B355_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B358_L[] = {
#include "textures/segment2/kr/kr_B358_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B358_R[] = {
#include "textures/segment2/kr/kr_B358_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B369_L[] = {
#include "textures/segment2/kr/kr_B369_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B369_R[] = {
#include "textures/segment2/kr/kr_B369_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B370_L[] = {
#include "textures/segment2/kr/kr_B370_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B370_R[] = {
#include "textures/segment2/kr/kr_B370_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B3C4_L[] = {
#include "textures/segment2/kr/kr_B3C4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B3C4_R[] = {
#include "textures/segment2/kr/kr_B3C4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B3C5_L[] = {
#include "textures/segment2/kr/kr_B3C5_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B3C5_R[] = {
#include "textures/segment2/kr/kr_B3C5_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B3CC_L[] = {
#include "textures/segment2/kr/kr_B3CC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B3CC_R[] = {
#include "textures/segment2/kr/kr_B3CC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B3D9_L[] = {
#include "textures/segment2/kr/kr_B3D9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B3D9_R[] = {
#include "textures/segment2/kr/kr_B3D9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B3FC_L[] = {
#include "textures/segment2/kr/kr_B3FC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B3FC_R[] = {
#include "textures/segment2/kr/kr_B3FC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B410_L[] = {
#include "textures/segment2/kr/kr_B410_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B410_R[] = {
#include "textures/segment2/kr/kr_B410_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B418_L[] = {
#include "textures/segment2/kr/kr_B418_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B418_R[] = {
#include "textures/segment2/kr/kr_B418_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B41C_L[] = {
#include "textures/segment2/kr/kr_B41C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B41C_R[] = {
#include "textures/segment2/kr/kr_B41C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B428_L[] = {
#include "textures/segment2/kr/kr_B428_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B428_R[] = {
#include "textures/segment2/kr/kr_B428_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B450_L[] = {
#include "textures/segment2/kr/kr_B450_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B450_R[] = {
#include "textures/segment2/kr/kr_B450_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B458_L[] = {
#include "textures/segment2/kr/kr_B458_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B458_R[] = {
#include "textures/segment2/kr/kr_B458_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B460_L[] = {
#include "textures/segment2/kr/kr_B460_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B460_R[] = {
#include "textures/segment2/kr/kr_B460_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B465_L[] = {
#include "textures/segment2/kr/kr_B465_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B465_R[] = {
#include "textures/segment2/kr/kr_B465_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B46C_L[] = {
#include "textures/segment2/kr/kr_B46C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B46C_R[] = {
#include "textures/segment2/kr/kr_B46C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4A4_L[] = {
#include "textures/segment2/kr/kr_B4A4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4A4_R[] = {
#include "textures/segment2/kr/kr_B4A4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4DC_L[] = {
#include "textures/segment2/kr/kr_B4DC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4DC_R[] = {
#include "textures/segment2/kr/kr_B4DC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4E0_L[] = {
#include "textures/segment2/kr/kr_B4E0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4E0_R[] = {
#include "textures/segment2/kr/kr_B4E0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4E4_L[] = {
#include "textures/segment2/kr/kr_B4E4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4E4_R[] = {
#include "textures/segment2/kr/kr_B4E4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4EF_L[] = {
#include "textures/segment2/kr/kr_B4EF_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4EF_R[] = {
#include "textures/segment2/kr/kr_B4EF_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4F1_L[] = {
#include "textures/segment2/kr/kr_B4F1_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B4F1_R[] = {
#include "textures/segment2/kr/kr_B4F1_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B514_L[] = {
#include "textures/segment2/kr/kr_B514_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B514_R[] = {
#include "textures/segment2/kr/kr_B514_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B518_L[] = {
#include "textures/segment2/kr/kr_B518_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B518_R[] = {
#include "textures/segment2/kr/kr_B518_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B54C_L[] = {
#include "textures/segment2/kr/kr_B54C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B54C_R[] = {
#include "textures/segment2/kr/kr_B54C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B5A0_L[] = {
#include "textures/segment2/kr/kr_B5A0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B5A0_R[] = {
#include "textures/segment2/kr/kr_B5A0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B5A8_L[] = {
#include "textures/segment2/kr/kr_B5A8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B5A8_R[] = {
#include "textures/segment2/kr/kr_B5A8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B69D_L[] = {
#include "textures/segment2/kr/kr_B69D_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B69D_R[] = {
#include "textures/segment2/kr/kr_B69D_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B6AB_L[] = {
#include "textures/segment2/kr/kr_B6AB_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B6AB_R[] = {
#include "textures/segment2/kr/kr_B6AB_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B6F0_L[] = {
#include "textures/segment2/kr/kr_B6F0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B6F0_R[] = {
#include "textures/segment2/kr/kr_B6F0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B728_L[] = {
#include "textures/segment2/kr/kr_B728_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B728_R[] = {
#include "textures/segment2/kr/kr_B728_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B77C_L[] = {
#include "textures/segment2/kr/kr_B77C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B77C_R[] = {
#include "textures/segment2/kr/kr_B77C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B78C_L[] = {
#include "textures/segment2/kr/kr_B78C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B78C_R[] = {
#include "textures/segment2/kr/kr_B78C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B791_L[] = {
#include "textures/segment2/kr/kr_B791_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B791_R[] = {
#include "textures/segment2/kr/kr_B791_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B798_L[] = {
#include "textures/segment2/kr/kr_B798_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B798_R[] = {
#include "textures/segment2/kr/kr_B798_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B7AD_L[] = {
#include "textures/segment2/kr/kr_B7AD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B7AD_R[] = {
#include "textures/segment2/kr/kr_B7AD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B7EC_L[] = {
#include "textures/segment2/kr/kr_B7EC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B7EC_R[] = {
#include "textures/segment2/kr/kr_B7EC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B7FC_L[] = {
#include "textures/segment2/kr/kr_B7FC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B7FC_R[] = {
#include "textures/segment2/kr/kr_B7FC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B801_L[] = {
#include "textures/segment2/kr/kr_B801_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B801_R[] = {
#include "textures/segment2/kr/kr_B801_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B808_L[] = {
#include "textures/segment2/kr/kr_B808_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B808_R[] = {
#include "textures/segment2/kr/kr_B808_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B824_L[] = {
#include "textures/segment2/kr/kr_B824_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B824_R[] = {
#include "textures/segment2/kr/kr_B824_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B825_L[] = {
#include "textures/segment2/kr/kr_B825_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B825_R[] = {
#include "textures/segment2/kr/kr_B825_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B839_L[] = {
#include "textures/segment2/kr/kr_B839_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B839_R[] = {
#include "textures/segment2/kr/kr_B839_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B85C_L[] = {
#include "textures/segment2/kr/kr_B85C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B85C_R[] = {
#include "textures/segment2/kr/kr_B85C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B85D_L[] = {
#include "textures/segment2/kr/kr_B85D_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B85D_R[] = {
#include "textures/segment2/kr/kr_B85D_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B8CC_L[] = {
#include "textures/segment2/kr/kr_B8CC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B8CC_R[] = {
#include "textures/segment2/kr/kr_B8CC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B8E8_L[] = {
#include "textures/segment2/kr/kr_B8E8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B8E8_R[] = {
#include "textures/segment2/kr/kr_B8E8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B958_L[] = {
#include "textures/segment2/kr/kr_B958_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B958_R[] = {
#include "textures/segment2/kr/kr_B958_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B974_L[] = {
#include "textures/segment2/kr/kr_B974_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B974_R[] = {
#include "textures/segment2/kr/kr_B974_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B978_L[] = {
#include "textures/segment2/kr/kr_B978_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B978_R[] = {
#include "textures/segment2/kr/kr_B978_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B97C_L[] = {
#include "textures/segment2/kr/kr_B97C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B97C_R[] = {
#include "textures/segment2/kr/kr_B97C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B984_L[] = {
#include "textures/segment2/kr/kr_B984_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B984_R[] = {
#include "textures/segment2/kr/kr_B984_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9AC_L[] = {
#include "textures/segment2/kr/kr_B9AC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9AC_R[] = {
#include "textures/segment2/kr/kr_B9AC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9AD_L[] = {
#include "textures/segment2/kr/kr_B9AD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9AD_R[] = {
#include "textures/segment2/kr/kr_B9AD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9B0_L[] = {
#include "textures/segment2/kr/kr_B9B0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9B0_R[] = {
#include "textures/segment2/kr/kr_B9B0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9BC_L[] = {
#include "textures/segment2/kr/kr_B9BC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9BC_R[] = {
#include "textures/segment2/kr/kr_B9BC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9BF_L[] = {
#include "textures/segment2/kr/kr_B9BF_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9BF_R[] = {
#include "textures/segment2/kr/kr_B9BF_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9C8_L[] = {
#include "textures/segment2/kr/kr_B9C8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9C8_R[] = {
#include "textures/segment2/kr/kr_B9C8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9C9_L[] = {
#include "textures/segment2/kr/kr_B9C9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9C9_R[] = {
#include "textures/segment2/kr/kr_B9C9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9CC_L[] = {
#include "textures/segment2/kr/kr_B9CC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9CC_R[] = {
#include "textures/segment2/kr/kr_B9CC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9D0_L[] = {
#include "textures/segment2/kr/kr_B9D0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9D0_R[] = {
#include "textures/segment2/kr/kr_B9D0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9DB_L[] = {
#include "textures/segment2/kr/kr_B9DB_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9DB_R[] = {
#include "textures/segment2/kr/kr_B9DB_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9DE_L[] = {
#include "textures/segment2/kr/kr_B9DE_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9DE_R[] = {
#include "textures/segment2/kr/kr_B9DE_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9E4_L[] = {
#include "textures/segment2/kr/kr_B9E4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_B9E4_R[] = {
#include "textures/segment2/kr/kr_B9E4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA38_L[] = {
#include "textures/segment2/kr/kr_BA38_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA38_R[] = {
#include "textures/segment2/kr/kr_BA38_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA3C_L[] = {
#include "textures/segment2/kr/kr_BA3C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA3C_R[] = {
#include "textures/segment2/kr/kr_BA3C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA48_L[] = {
#include "textures/segment2/kr/kr_BA48_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA48_R[] = {
#include "textures/segment2/kr/kr_BA48_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA4D_L[] = {
#include "textures/segment2/kr/kr_BA4D_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA4D_R[] = {
#include "textures/segment2/kr/kr_BA4D_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA54_L[] = {
#include "textures/segment2/kr/kr_BA54_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA54_R[] = {
#include "textures/segment2/kr/kr_BA54_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA74_L[] = {
#include "textures/segment2/kr/kr_BA74_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA74_R[] = {
#include "textures/segment2/kr/kr_BA74_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA85_L[] = {
#include "textures/segment2/kr/kr_BA85_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BA85_R[] = {
#include "textures/segment2/kr/kr_BA85_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BAA8_L[] = {
#include "textures/segment2/kr/kr_BAA8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BAA8_R[] = {
#include "textures/segment2/kr/kr_BAA8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BAA9_L[] = {
#include "textures/segment2/kr/kr_BAA9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BAA9_R[] = {
#include "textures/segment2/kr/kr_BAA9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BAB8_L[] = {
#include "textures/segment2/kr/kr_BAB8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BAB8_R[] = {
#include "textures/segment2/kr/kr_BAB8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BABB_L[] = {
#include "textures/segment2/kr/kr_BABB_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BABB_R[] = {
#include "textures/segment2/kr/kr_BABB_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BB34_L[] = {
#include "textures/segment2/kr/kr_BB34_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BB34_R[] = {
#include "textures/segment2/kr/kr_BB34_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BB38_L[] = {
#include "textures/segment2/kr/kr_BB38_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BB38_R[] = {
#include "textures/segment2/kr/kr_BB38_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BB3C_L[] = {
#include "textures/segment2/kr/kr_BB3C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BB3C_R[] = {
#include "textures/segment2/kr/kr_BB3C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BBF8_L[] = {
#include "textures/segment2/kr/kr_BBF8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BBF8_R[] = {
#include "textures/segment2/kr/kr_BBF8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC00_L[] = {
#include "textures/segment2/kr/kr_BC00_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC00_R[] = {
#include "textures/segment2/kr/kr_BC00_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC0D_L[] = {
#include "textures/segment2/kr/kr_BC0D_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC0D_R[] = {
#include "textures/segment2/kr/kr_BC0D_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC11_L[] = {
#include "textures/segment2/kr/kr_BC11_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC11_R[] = {
#include "textures/segment2/kr/kr_BC11_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC14_L[] = {
#include "textures/segment2/kr/kr_BC14_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC14_R[] = {
#include "textures/segment2/kr/kr_BC14_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC18_L[] = {
#include "textures/segment2/kr/kr_BC18_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC18_R[] = {
#include "textures/segment2/kr/kr_BC18_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC1C_L[] = {
#include "textures/segment2/kr/kr_BC1C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC1C_R[] = {
#include "textures/segment2/kr/kr_BC1C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC1F_L[] = {
#include "textures/segment2/kr/kr_BC1F_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC1F_R[] = {
#include "textures/segment2/kr/kr_BC1F_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC25_L[] = {
#include "textures/segment2/kr/kr_BC25_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC25_R[] = {
#include "textures/segment2/kr/kr_BC25_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC29_L[] = {
#include "textures/segment2/kr/kr_BC29_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC29_R[] = {
#include "textures/segment2/kr/kr_BC29_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC30_L[] = {
#include "textures/segment2/kr/kr_BC30_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC30_R[] = {
#include "textures/segment2/kr/kr_BC30_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC84_L[] = {
#include "textures/segment2/kr/kr_BC84_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC84_R[] = {
#include "textures/segment2/kr/kr_BC84_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC88_L[] = {
#include "textures/segment2/kr/kr_BC88_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BC88_R[] = {
#include "textures/segment2/kr/kr_BC88_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCA0_L[] = {
#include "textures/segment2/kr/kr_BCA0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCA0_R[] = {
#include "textures/segment2/kr/kr_BCA0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCBD_L[] = {
#include "textures/segment2/kr/kr_BCBD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCBD_R[] = {
#include "textures/segment2/kr/kr_BCBD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCC4_L[] = {
#include "textures/segment2/kr/kr_BCC4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCC4_R[] = {
#include "textures/segment2/kr/kr_BCC4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCF4_L[] = {
#include "textures/segment2/kr/kr_BCF4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCF4_R[] = {
#include "textures/segment2/kr/kr_BCF4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCF5_L[] = {
#include "textures/segment2/kr/kr_BCF5_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCF5_R[] = {
#include "textures/segment2/kr/kr_BCF5_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCFC_L[] = {
#include "textures/segment2/kr/kr_BCFC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BCFC_R[] = {
#include "textures/segment2/kr/kr_BCFC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BD10_L[] = {
#include "textures/segment2/kr/kr_BD10_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BD10_R[] = {
#include "textures/segment2/kr/kr_BD10_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BD80_L[] = {
#include "textures/segment2/kr/kr_BD80_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BD80_R[] = {
#include "textures/segment2/kr/kr_BD80_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BD84_L[] = {
#include "textures/segment2/kr/kr_BD84_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BD84_R[] = {
#include "textures/segment2/kr/kr_BD84_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BD88_L[] = {
#include "textures/segment2/kr/kr_BD88_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BD88_R[] = {
#include "textures/segment2/kr/kr_BD88_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BD99_L[] = {
#include "textures/segment2/kr/kr_BD99_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BD99_R[] = {
#include "textures/segment2/kr/kr_BD99_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE44_L[] = {
#include "textures/segment2/kr/kr_BE44_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE44_R[] = {
#include "textures/segment2/kr/kr_BE44_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE45_L[] = {
#include "textures/segment2/kr/kr_BE45_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE45_R[] = {
#include "textures/segment2/kr/kr_BE45_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE48_L[] = {
#include "textures/segment2/kr/kr_BE48_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE48_R[] = {
#include "textures/segment2/kr/kr_BE48_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE5B_L[] = {
#include "textures/segment2/kr/kr_BE5B_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE5B_R[] = {
#include "textures/segment2/kr/kr_BE5B_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE60_L[] = {
#include "textures/segment2/kr/kr_BE60_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE60_R[] = {
#include "textures/segment2/kr/kr_BE60_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE68_L[] = {
#include "textures/segment2/kr/kr_BE68_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BE68_R[] = {
#include "textures/segment2/kr/kr_BE68_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BED0_L[] = {
#include "textures/segment2/kr/kr_BED0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BED0_R[] = {
#include "textures/segment2/kr/kr_BED0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BF51_L[] = {
#include "textures/segment2/kr/kr_BF51_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_BF51_R[] = {
#include "textures/segment2/kr/kr_BF51_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0AC_L[] = {
#include "textures/segment2/kr/kr_C0AC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0AC_R[] = {
#include "textures/segment2/kr/kr_C0AC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0AD_L[] = {
#include "textures/segment2/kr/kr_C0AD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0AD_R[] = {
#include "textures/segment2/kr/kr_C0AD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0B0_L[] = {
#include "textures/segment2/kr/kr_C0B0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0B0_R[] = {
#include "textures/segment2/kr/kr_C0B0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0B4_L[] = {
#include "textures/segment2/kr/kr_C0B4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0B4_R[] = {
#include "textures/segment2/kr/kr_C0B4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0BC_L[] = {
#include "textures/segment2/kr/kr_C0BC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0BC_R[] = {
#include "textures/segment2/kr/kr_C0BC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0C1_L[] = {
#include "textures/segment2/kr/kr_C0C1_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0C1_R[] = {
#include "textures/segment2/kr/kr_C0C1_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0C8_L[] = {
#include "textures/segment2/kr/kr_C0C8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0C8_R[] = {
#include "textures/segment2/kr/kr_C0C8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0DD_L[] = {
#include "textures/segment2/kr/kr_C0DD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C0DD_R[] = {
#include "textures/segment2/kr/kr_C0DD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C11C_L[] = {
#include "textures/segment2/kr/kr_C11C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C11C_R[] = {
#include "textures/segment2/kr/kr_C11C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C120_L[] = {
#include "textures/segment2/kr/kr_C120_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C120_R[] = {
#include "textures/segment2/kr/kr_C120_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C12C_L[] = {
#include "textures/segment2/kr/kr_C12C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C12C_R[] = {
#include "textures/segment2/kr/kr_C12C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C12F_L[] = {
#include "textures/segment2/kr/kr_C12F_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C12F_R[] = {
#include "textures/segment2/kr/kr_C12F_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C131_L[] = {
#include "textures/segment2/kr/kr_C131_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C131_R[] = {
#include "textures/segment2/kr/kr_C131_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C138_L[] = {
#include "textures/segment2/kr/kr_C138_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C138_R[] = {
#include "textures/segment2/kr/kr_C138_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C18D_L[] = {
#include "textures/segment2/kr/kr_C18D_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C18D_R[] = {
#include "textures/segment2/kr/kr_C18D_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C190_L[] = {
#include "textures/segment2/kr/kr_C190_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C190_R[] = {
#include "textures/segment2/kr/kr_C190_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C1E0_L[] = {
#include "textures/segment2/kr/kr_C1E0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C1E0_R[] = {
#include "textures/segment2/kr/kr_C1E0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C218_L[] = {
#include "textures/segment2/kr/kr_C218_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C218_R[] = {
#include "textures/segment2/kr/kr_C218_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C228_L[] = {
#include "textures/segment2/kr/kr_C228_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C228_R[] = {
#include "textures/segment2/kr/kr_C228_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C22D_L[] = {
#include "textures/segment2/kr/kr_C22D_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C22D_R[] = {
#include "textures/segment2/kr/kr_C22D_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C234_L[] = {
#include "textures/segment2/kr/kr_C234_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C234_R[] = {
#include "textures/segment2/kr/kr_C234_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2A4_L[] = {
#include "textures/segment2/kr/kr_C2A4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2A4_R[] = {
#include "textures/segment2/kr/kr_C2A4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2AC_L[] = {
#include "textures/segment2/kr/kr_C2AC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2AC_R[] = {
#include "textures/segment2/kr/kr_C2AC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2AD_L[] = {
#include "textures/segment2/kr/kr_C2AD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2AD_R[] = {
#include "textures/segment2/kr/kr_C2AD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2B5_L[] = {
#include "textures/segment2/kr/kr_C2B5_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2B5_R[] = {
#include "textures/segment2/kr/kr_C2B5_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2B9_L[] = {
#include "textures/segment2/kr/kr_C2B9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2B9_R[] = {
#include "textures/segment2/kr/kr_C2B9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2DC_L[] = {
#include "textures/segment2/kr/kr_C2DC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2DC_R[] = {
#include "textures/segment2/kr/kr_C2DC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2E0_L[] = {
#include "textures/segment2/kr/kr_C2E0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2E0_R[] = {
#include "textures/segment2/kr/kr_C2E0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2E4_L[] = {
#include "textures/segment2/kr/kr_C2E4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2E4_R[] = {
#include "textures/segment2/kr/kr_C2E4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2EC_L[] = {
#include "textures/segment2/kr/kr_C2EC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2EC_R[] = {
#include "textures/segment2/kr/kr_C2EC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2F6_L[] = {
#include "textures/segment2/kr/kr_C2F6_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2F6_R[] = {
#include "textures/segment2/kr/kr_C2F6_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2F8_L[] = {
#include "textures/segment2/kr/kr_C2F8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2F8_R[] = {
#include "textures/segment2/kr/kr_C2F8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2FC_L[] = {
#include "textures/segment2/kr/kr_C2FC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C2FC_R[] = {
#include "textures/segment2/kr/kr_C2FC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C313_L[] = {
#include "textures/segment2/kr/kr_C313_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C313_R[] = {
#include "textures/segment2/kr/kr_C313_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C368_L[] = {
#include "textures/segment2/kr/kr_C368_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C368_R[] = {
#include "textures/segment2/kr/kr_C368_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C370_L[] = {
#include "textures/segment2/kr/kr_C370_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C370_R[] = {
#include "textures/segment2/kr/kr_C370_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C384_L[] = {
#include "textures/segment2/kr/kr_C384_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C384_R[] = {
#include "textures/segment2/kr/kr_C384_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C544_L[] = {
#include "textures/segment2/kr/kr_C544_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C544_R[] = {
#include "textures/segment2/kr/kr_C544_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C548_L[] = {
#include "textures/segment2/kr/kr_C548_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C548_R[] = {
#include "textures/segment2/kr/kr_C548_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C549_L[] = {
#include "textures/segment2/kr/kr_C549_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C549_R[] = {
#include "textures/segment2/kr/kr_C549_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C54A_L[] = {
#include "textures/segment2/kr/kr_C54A_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C54A_R[] = {
#include "textures/segment2/kr/kr_C54A_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C554_L[] = {
#include "textures/segment2/kr/kr_C554_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C554_R[] = {
#include "textures/segment2/kr/kr_C554_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C558_L[] = {
#include "textures/segment2/kr/kr_C558_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C558_R[] = {
#include "textures/segment2/kr/kr_C558_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C55E_L[] = {
#include "textures/segment2/kr/kr_C55E_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C55E_R[] = {
#include "textures/segment2/kr/kr_C55E_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C57C_L[] = {
#include "textures/segment2/kr/kr_C57C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C57C_R[] = {
#include "textures/segment2/kr/kr_C57C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C595_L[] = {
#include "textures/segment2/kr/kr_C595_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C595_R[] = {
#include "textures/segment2/kr/kr_C595_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5B4_L[] = {
#include "textures/segment2/kr/kr_C5B4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5B4_R[] = {
#include "textures/segment2/kr/kr_C5B4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5B8_L[] = {
#include "textures/segment2/kr/kr_C5B8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5B8_R[] = {
#include "textures/segment2/kr/kr_C5B8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5BC_L[] = {
#include "textures/segment2/kr/kr_C5BC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5BC_R[] = {
#include "textures/segment2/kr/kr_C5BC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5C4_L[] = {
#include "textures/segment2/kr/kr_C5C4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5C4_R[] = {
#include "textures/segment2/kr/kr_C5C4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5C6_L[] = {
#include "textures/segment2/kr/kr_C5C6_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5C6_R[] = {
#include "textures/segment2/kr/kr_C5C6_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5D0_L[] = {
#include "textures/segment2/kr/kr_C5D0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5D0_R[] = {
#include "textures/segment2/kr/kr_C5D0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5D8_L[] = {
#include "textures/segment2/kr/kr_C5D8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5D8_R[] = {
#include "textures/segment2/kr/kr_C5D8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5EC_L[] = {
#include "textures/segment2/kr/kr_C5EC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5EC_R[] = {
#include "textures/segment2/kr/kr_C5EC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5F0_L[] = {
#include "textures/segment2/kr/kr_C5F0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5F0_R[] = {
#include "textures/segment2/kr/kr_C5F0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5F4_L[] = {
#include "textures/segment2/kr/kr_C5F4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C5F4_R[] = {
#include "textures/segment2/kr/kr_C5F4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C608_L[] = {
#include "textures/segment2/kr/kr_C608_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C608_R[] = {
#include "textures/segment2/kr/kr_C608_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C624_L[] = {
#include "textures/segment2/kr/kr_C624_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C624_R[] = {
#include "textures/segment2/kr/kr_C624_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C62C_L[] = {
#include "textures/segment2/kr/kr_C62C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C62C_R[] = {
#include "textures/segment2/kr/kr_C62C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C634_L[] = {
#include "textures/segment2/kr/kr_C634_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C634_R[] = {
#include "textures/segment2/kr/kr_C634_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C640_L[] = {
#include "textures/segment2/kr/kr_C640_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C640_R[] = {
#include "textures/segment2/kr/kr_C640_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C644_L[] = {
#include "textures/segment2/kr/kr_C644_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C644_R[] = {
#include "textures/segment2/kr/kr_C644_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C654_L[] = {
#include "textures/segment2/kr/kr_C654_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C654_R[] = {
#include "textures/segment2/kr/kr_C654_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C678_L[] = {
#include "textures/segment2/kr/kr_C678_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C678_R[] = {
#include "textures/segment2/kr/kr_C678_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C67C_L[] = {
#include "textures/segment2/kr/kr_C67C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C67C_R[] = {
#include "textures/segment2/kr/kr_C67C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C694_L[] = {
#include "textures/segment2/kr/kr_C694_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C694_R[] = {
#include "textures/segment2/kr/kr_C694_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6A9_L[] = {
#include "textures/segment2/kr/kr_C6A9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6A9_R[] = {
#include "textures/segment2/kr/kr_C6A9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6B0_L[] = {
#include "textures/segment2/kr/kr_C6B0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6B0_R[] = {
#include "textures/segment2/kr/kr_C6B0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6B4_L[] = {
#include "textures/segment2/kr/kr_C6B4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6B4_R[] = {
#include "textures/segment2/kr/kr_C6B4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6C0_L[] = {
#include "textures/segment2/kr/kr_C6C0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6C0_R[] = {
#include "textures/segment2/kr/kr_C6C0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6CC_L[] = {
#include "textures/segment2/kr/kr_C6CC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6CC_R[] = {
#include "textures/segment2/kr/kr_C6CC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6D0_L[] = {
#include "textures/segment2/kr/kr_C6D0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6D0_R[] = {
#include "textures/segment2/kr/kr_C6D0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6DC_L[] = {
#include "textures/segment2/kr/kr_C6DC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C6DC_R[] = {
#include "textures/segment2/kr/kr_C6DC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C704_L[] = {
#include "textures/segment2/kr/kr_C704_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C704_R[] = {
#include "textures/segment2/kr/kr_C704_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C720_L[] = {
#include "textures/segment2/kr/kr_C720_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C720_R[] = {
#include "textures/segment2/kr/kr_C720_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C73C_L[] = {
#include "textures/segment2/kr/kr_C73C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C73C_R[] = {
#include "textures/segment2/kr/kr_C73C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C740_L[] = {
#include "textures/segment2/kr/kr_C740_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C740_R[] = {
#include "textures/segment2/kr/kr_C740_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C744_L[] = {
#include "textures/segment2/kr/kr_C744_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C744_R[] = {
#include "textures/segment2/kr/kr_C744_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C74C_L[] = {
#include "textures/segment2/kr/kr_C74C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C74C_R[] = {
#include "textures/segment2/kr/kr_C74C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C758_L[] = {
#include "textures/segment2/kr/kr_C758_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C758_R[] = {
#include "textures/segment2/kr/kr_C758_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C774_L[] = {
#include "textures/segment2/kr/kr_C774_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C774_R[] = {
#include "textures/segment2/kr/kr_C774_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C778_L[] = {
#include "textures/segment2/kr/kr_C778_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C778_R[] = {
#include "textures/segment2/kr/kr_C778_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C77C_L[] = {
#include "textures/segment2/kr/kr_C77C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C77C_R[] = {
#include "textures/segment2/kr/kr_C77C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C77D_L[] = {
#include "textures/segment2/kr/kr_C77D_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C77D_R[] = {
#include "textures/segment2/kr/kr_C77D_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C783_L[] = {
#include "textures/segment2/kr/kr_C783_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C783_R[] = {
#include "textures/segment2/kr/kr_C783_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C784_L[] = {
#include "textures/segment2/kr/kr_C784_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C784_R[] = {
#include "textures/segment2/kr/kr_C784_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C788_L[] = {
#include "textures/segment2/kr/kr_C788_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C788_R[] = {
#include "textures/segment2/kr/kr_C788_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C790_L[] = {
#include "textures/segment2/kr/kr_C790_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C790_R[] = {
#include "textures/segment2/kr/kr_C790_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C791_L[] = {
#include "textures/segment2/kr/kr_C791_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C791_R[] = {
#include "textures/segment2/kr/kr_C791_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C796_L[] = {
#include "textures/segment2/kr/kr_C796_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C796_R[] = {
#include "textures/segment2/kr/kr_C796_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C798_L[] = {
#include "textures/segment2/kr/kr_C798_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C798_R[] = {
#include "textures/segment2/kr/kr_C798_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7A0_L[] = {
#include "textures/segment2/kr/kr_C7A0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7A0_R[] = {
#include "textures/segment2/kr/kr_C7A0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7A1_L[] = {
#include "textures/segment2/kr/kr_C7A1_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7A1_R[] = {
#include "textures/segment2/kr/kr_C7A1_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7A5_L[] = {
#include "textures/segment2/kr/kr_C7A5_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7A5_R[] = {
#include "textures/segment2/kr/kr_C7A5_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7AC_L[] = {
#include "textures/segment2/kr/kr_C7AC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7AC_R[] = {
#include "textures/segment2/kr/kr_C7AC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7BD_L[] = {
#include "textures/segment2/kr/kr_C7BD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7BD_R[] = {
#include "textures/segment2/kr/kr_C7BD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7C1_L[] = {
#include "textures/segment2/kr/kr_C7C1_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C7C1_R[] = {
#include "textures/segment2/kr/kr_C7C1_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C800_L[] = {
#include "textures/segment2/kr/kr_C800_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C800_R[] = {
#include "textures/segment2/kr/kr_C800_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C801_L[] = {
#include "textures/segment2/kr/kr_C801_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C801_R[] = {
#include "textures/segment2/kr/kr_C801_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C804_L[] = {
#include "textures/segment2/kr/kr_C804_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C804_R[] = {
#include "textures/segment2/kr/kr_C804_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C808_L[] = {
#include "textures/segment2/kr/kr_C808_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C808_R[] = {
#include "textures/segment2/kr/kr_C808_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C810_L[] = {
#include "textures/segment2/kr/kr_C810_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C810_R[] = {
#include "textures/segment2/kr/kr_C810_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C815_L[] = {
#include "textures/segment2/kr/kr_C815_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C815_R[] = {
#include "textures/segment2/kr/kr_C815_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C81C_L[] = {
#include "textures/segment2/kr/kr_C81C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C81C_R[] = {
#include "textures/segment2/kr/kr_C81C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C838_L[] = {
#include "textures/segment2/kr/kr_C838_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C838_R[] = {
#include "textures/segment2/kr/kr_C838_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C870_L[] = {
#include "textures/segment2/kr/kr_C870_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C870_R[] = {
#include "textures/segment2/kr/kr_C870_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C871_L[] = {
#include "textures/segment2/kr/kr_C871_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C871_R[] = {
#include "textures/segment2/kr/kr_C871_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C878_L[] = {
#include "textures/segment2/kr/kr_C878_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C878_R[] = {
#include "textures/segment2/kr/kr_C878_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C885_L[] = {
#include "textures/segment2/kr/kr_C885_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C885_R[] = {
#include "textures/segment2/kr/kr_C885_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C88B_L[] = {
#include "textures/segment2/kr/kr_C88B_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C88B_R[] = {
#include "textures/segment2/kr/kr_C88B_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C8FC_L[] = {
#include "textures/segment2/kr/kr_C8FC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C8FC_R[] = {
#include "textures/segment2/kr/kr_C8FC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C900_L[] = {
#include "textures/segment2/kr/kr_C900_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C900_R[] = {
#include "textures/segment2/kr/kr_C900_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C904_L[] = {
#include "textures/segment2/kr/kr_C904_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C904_R[] = {
#include "textures/segment2/kr/kr_C904_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C911_L[] = {
#include "textures/segment2/kr/kr_C911_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C911_R[] = {
#include "textures/segment2/kr/kr_C911_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C918_L[] = {
#include "textures/segment2/kr/kr_C918_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C918_R[] = {
#include "textures/segment2/kr/kr_C918_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C950_L[] = {
#include "textures/segment2/kr/kr_C950_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C950_R[] = {
#include "textures/segment2/kr/kr_C950_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C990_L[] = {
#include "textures/segment2/kr/kr_C990_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C990_R[] = {
#include "textures/segment2/kr/kr_C990_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9C0_L[] = {
#include "textures/segment2/kr/kr_C9C0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9C0_R[] = {
#include "textures/segment2/kr/kr_C9C0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9C1_L[] = {
#include "textures/segment2/kr/kr_C9C1_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9C1_R[] = {
#include "textures/segment2/kr/kr_C9C1_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9C4_L[] = {
#include "textures/segment2/kr/kr_C9C4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9C4_R[] = {
#include "textures/segment2/kr/kr_C9C4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9C8_L[] = {
#include "textures/segment2/kr/kr_C9C8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9C8_R[] = {
#include "textures/segment2/kr/kr_C9C8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9D1_L[] = {
#include "textures/segment2/kr/kr_C9D1_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9D1_R[] = {
#include "textures/segment2/kr/kr_C9D1_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9DC_L[] = {
#include "textures/segment2/kr/kr_C9DC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9DC_R[] = {
#include "textures/segment2/kr/kr_C9DC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9F8_L[] = {
#include "textures/segment2/kr/kr_C9F8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_C9F8_R[] = {
#include "textures/segment2/kr/kr_C9F8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CABD_L[] = {
#include "textures/segment2/kr/kr_CABD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CABD_R[] = {
#include "textures/segment2/kr/kr_CABD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC0C_L[] = {
#include "textures/segment2/kr/kr_CC0C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC0C_R[] = {
#include "textures/segment2/kr/kr_CC0C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC28_L[] = {
#include "textures/segment2/kr/kr_CC28_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC28_R[] = {
#include "textures/segment2/kr/kr_CC28_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC2C_L[] = {
#include "textures/segment2/kr/kr_CC2C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC2C_R[] = {
#include "textures/segment2/kr/kr_CC2C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC3E_L[] = {
#include "textures/segment2/kr/kr_CC3E_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC3E_R[] = {
#include "textures/segment2/kr/kr_CC3E_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC45_L[] = {
#include "textures/segment2/kr/kr_CC45_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC45_R[] = {
#include "textures/segment2/kr/kr_CC45_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC98_L[] = {
#include "textures/segment2/kr/kr_CC98_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CC98_R[] = {
#include "textures/segment2/kr/kr_CC98_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CCD0_L[] = {
#include "textures/segment2/kr/kr_CCD0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CCD0_R[] = {
#include "textures/segment2/kr/kr_CCD0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CD08_L[] = {
#include "textures/segment2/kr/kr_CD08_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CD08_R[] = {
#include "textures/segment2/kr/kr_CD08_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CD5C_L[] = {
#include "textures/segment2/kr/kr_CD5C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CD5C_R[] = {
#include "textures/segment2/kr/kr_CD5C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CD95_L[] = {
#include "textures/segment2/kr/kr_CD95_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CD95_R[] = {
#include "textures/segment2/kr/kr_CD95_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CD9C_L[] = {
#include "textures/segment2/kr/kr_CD9C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CD9C_R[] = {
#include "textures/segment2/kr/kr_CD9C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CDA9_L[] = {
#include "textures/segment2/kr/kr_CDA9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CDA9_R[] = {
#include "textures/segment2/kr/kr_CDA9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CDB0_L[] = {
#include "textures/segment2/kr/kr_CDB0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CDB0_R[] = {
#include "textures/segment2/kr/kr_CDB0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CE58_L[] = {
#include "textures/segment2/kr/kr_CE58_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CE58_R[] = {
#include "textures/segment2/kr/kr_CE58_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CE5C_L[] = {
#include "textures/segment2/kr/kr_CE5C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CE5C_R[] = {
#include "textures/segment2/kr/kr_CE5C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CE74_L[] = {
#include "textures/segment2/kr/kr_CE74_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CE74_R[] = {
#include "textures/segment2/kr/kr_CE74_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CE90_L[] = {
#include "textures/segment2/kr/kr_CE90_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CE90_R[] = {
#include "textures/segment2/kr/kr_CE90_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CF00_L[] = {
#include "textures/segment2/kr/kr_CF00_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CF00_R[] = {
#include "textures/segment2/kr/kr_CF00_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CF54_L[] = {
#include "textures/segment2/kr/kr_CF54_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CF54_R[] = {
#include "textures/segment2/kr/kr_CF54_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CFE0_L[] = {
#include "textures/segment2/kr/kr_CFE0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CFE0_R[] = {
#include "textures/segment2/kr/kr_CFE0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CFE8_L[] = {
#include "textures/segment2/kr/kr_CFE8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_CFE8_R[] = {
#include "textures/segment2/kr/kr_CFE8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D06C_L[] = {
#include "textures/segment2/kr/kr_D06C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D06C_R[] = {
#include "textures/segment2/kr/kr_D06C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D070_L[] = {
#include "textures/segment2/kr/kr_D070_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D070_R[] = {
#include "textures/segment2/kr/kr_D070_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D074_L[] = {
#include "textures/segment2/kr/kr_D074_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D074_R[] = {
#include "textures/segment2/kr/kr_D074_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D07C_L[] = {
#include "textures/segment2/kr/kr_D07C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D07C_R[] = {
#include "textures/segment2/kr/kr_D07C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0A4_L[] = {
#include "textures/segment2/kr/kr_D0A4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0A4_R[] = {
#include "textures/segment2/kr/kr_D0A4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0B9_L[] = {
#include "textures/segment2/kr/kr_D0B9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0B9_R[] = {
#include "textures/segment2/kr/kr_D0B9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0C0_L[] = {
#include "textures/segment2/kr/kr_D0C0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0C0_R[] = {
#include "textures/segment2/kr/kr_D0C0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0C4_L[] = {
#include "textures/segment2/kr/kr_D0C4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0C4_R[] = {
#include "textures/segment2/kr/kr_D0C4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0C8_L[] = {
#include "textures/segment2/kr/kr_D0C8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0C8_R[] = {
#include "textures/segment2/kr/kr_D0C8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0D1_L[] = {
#include "textures/segment2/kr/kr_D0D1_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0D1_R[] = {
#include "textures/segment2/kr/kr_D0D1_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0DD_L[] = {
#include "textures/segment2/kr/kr_D0DD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D0DD_R[] = {
#include "textures/segment2/kr/kr_D0DD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D130_L[] = {
#include "textures/segment2/kr/kr_D130_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D130_R[] = {
#include "textures/segment2/kr/kr_D130_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D14C_L[] = {
#include "textures/segment2/kr/kr_D14C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D14C_R[] = {
#include "textures/segment2/kr/kr_D14C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D1A4_L[] = {
#include "textures/segment2/kr/kr_D1A4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D1A4_R[] = {
#include "textures/segment2/kr/kr_D1A4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D1B1_L[] = {
#include "textures/segment2/kr/kr_D1B1_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D1B1_R[] = {
#include "textures/segment2/kr/kr_D1B1_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D1B5_L[] = {
#include "textures/segment2/kr/kr_D1B5_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D1B5_R[] = {
#include "textures/segment2/kr/kr_D1B5_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D22C_L[] = {
#include "textures/segment2/kr/kr_D22C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D22C_R[] = {
#include "textures/segment2/kr/kr_D22C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2B8_L[] = {
#include "textures/segment2/kr/kr_D2B8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2B8_R[] = {
#include "textures/segment2/kr/kr_D2B8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2B9_L[] = {
#include "textures/segment2/kr/kr_D2B9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2B9_R[] = {
#include "textures/segment2/kr/kr_D2B9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2BC_L[] = {
#include "textures/segment2/kr/kr_D2BC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2BC_R[] = {
#include "textures/segment2/kr/kr_D2BC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2C0_L[] = {
#include "textures/segment2/kr/kr_D2C0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2C0_R[] = {
#include "textures/segment2/kr/kr_D2C0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2C8_L[] = {
#include "textures/segment2/kr/kr_D2C8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2C8_R[] = {
#include "textures/segment2/kr/kr_D2C8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2F4_L[] = {
#include "textures/segment2/kr/kr_D2F4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D2F4_R[] = {
#include "textures/segment2/kr/kr_D2F4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D30C_L[] = {
#include "textures/segment2/kr/kr_D30C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D30C_R[] = {
#include "textures/segment2/kr/kr_D30C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D310_L[] = {
#include "textures/segment2/kr/kr_D310_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D310_R[] = {
#include "textures/segment2/kr/kr_D310_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D37C_L[] = {
#include "textures/segment2/kr/kr_D37C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D37C_R[] = {
#include "textures/segment2/kr/kr_D37C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3AD_L[] = {
#include "textures/segment2/kr/kr_D3AD_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3AD_R[] = {
#include "textures/segment2/kr/kr_D3AD_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3B8_L[] = {
#include "textures/segment2/kr/kr_D3B8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3B8_R[] = {
#include "textures/segment2/kr/kr_D3B8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3C9_L[] = {
#include "textures/segment2/kr/kr_D3C9_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3C9_R[] = {
#include "textures/segment2/kr/kr_D3C9_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3EC_L[] = {
#include "textures/segment2/kr/kr_D3EC_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3EC_R[] = {
#include "textures/segment2/kr/kr_D3EC_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3ED_L[] = {
#include "textures/segment2/kr/kr_D3ED_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3ED_R[] = {
#include "textures/segment2/kr/kr_D3ED_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3F0_L[] = {
#include "textures/segment2/kr/kr_D3F0_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D3F0_R[] = {
#include "textures/segment2/kr/kr_D3F0_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D45C_L[] = {
#include "textures/segment2/kr/kr_D45C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D45C_R[] = {
#include "textures/segment2/kr/kr_D45C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D478_L[] = {
#include "textures/segment2/kr/kr_D478_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D478_R[] = {
#include "textures/segment2/kr/kr_D478_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D504_L[] = {
#include "textures/segment2/kr/kr_D504_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D504_R[] = {
#include "textures/segment2/kr/kr_D504_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D50C_L[] = {
#include "textures/segment2/kr/kr_D50C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D50C_R[] = {
#include "textures/segment2/kr/kr_D50C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D53C_L[] = {
#include "textures/segment2/kr/kr_D53C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D53C_R[] = {
#include "textures/segment2/kr/kr_D53C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D558_L[] = {
#include "textures/segment2/kr/kr_D558_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D558_R[] = {
#include "textures/segment2/kr/kr_D558_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D55C_L[] = {
#include "textures/segment2/kr/kr_D55C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D55C_R[] = {
#include "textures/segment2/kr/kr_D55C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D560_L[] = {
#include "textures/segment2/kr/kr_D560_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D560_R[] = {
#include "textures/segment2/kr/kr_D560_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D568_L[] = {
#include "textures/segment2/kr/kr_D568_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D568_R[] = {
#include "textures/segment2/kr/kr_D568_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D569_L[] = {
#include "textures/segment2/kr/kr_D569_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D569_R[] = {
#include "textures/segment2/kr/kr_D569_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D56D_L[] = {
#include "textures/segment2/kr/kr_D56D_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D56D_R[] = {
#include "textures/segment2/kr/kr_D56D_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D574_L[] = {
#include "textures/segment2/kr/kr_D574_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D574_R[] = {
#include "textures/segment2/kr/kr_D574_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D589_L[] = {
#include "textures/segment2/kr/kr_D589_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D589_R[] = {
#include "textures/segment2/kr/kr_D589_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D5D8_L[] = {
#include "textures/segment2/kr/kr_D5D8_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D5D8_R[] = {
#include "textures/segment2/kr/kr_D5D8_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D5E4_L[] = {
#include "textures/segment2/kr/kr_D5E4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D5E4_R[] = {
#include "textures/segment2/kr/kr_D5E4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D615_L[] = {
#include "textures/segment2/kr/kr_D615_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D615_R[] = {
#include "textures/segment2/kr/kr_D615_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D654_L[] = {
#include "textures/segment2/kr/kr_D654_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D654_R[] = {
#include "textures/segment2/kr/kr_D654_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D655_L[] = {
#include "textures/segment2/kr/kr_D655_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D655_R[] = {
#include "textures/segment2/kr/kr_D655_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D68C_L[] = {
#include "textures/segment2/kr/kr_D68C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D68C_R[] = {
#include "textures/segment2/kr/kr_D68C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D6D4_L[] = {
#include "textures/segment2/kr/kr_D6D4_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D6D4_R[] = {
#include "textures/segment2/kr/kr_D6D4_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D754_L[] = {
#include "textures/segment2/kr/kr_D754_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D754_R[] = {
#include "textures/segment2/kr/kr_D754_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D788_L[] = {
#include "textures/segment2/kr/kr_D788_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D788_R[] = {
#include "textures/segment2/kr/kr_D788_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D78C_L[] = {
#include "textures/segment2/kr/kr_D78C_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D78C_R[] = {
#include "textures/segment2/kr/kr_D78C_R.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D798_L[] = {
#include "textures/segment2/kr/kr_D798_L.ia4.inc.c"
};
ALIGNED8 static const Texture kr_g_D798_R[] = {
#include "textures/segment2/kr/kr_D798_R.ia4.inc.c"
};

const Texture *const kr_glyphs[] = {
    kr_g_AC00_L, kr_g_AC00_R,
    kr_g_AC01_L, kr_g_AC01_R,
    kr_g_AC04_L, kr_g_AC04_R,
    kr_g_AC07_L, kr_g_AC07_R,
    kr_g_AC15_L, kr_g_AC15_R,
    kr_g_AC1C_L, kr_g_AC1C_R,
    kr_g_AC70_L, kr_g_AC70_R,
    kr_g_AC74_L, kr_g_AC74_R,
    kr_g_AC78_L, kr_g_AC78_R,
    kr_g_AC8C_L, kr_g_AC8C_R,
    kr_g_ACA0_L, kr_g_ACA0_R,
    kr_g_ACA8_L, kr_g_ACA8_R,
    kr_g_ACA9_L, kr_g_ACA9_R,
    kr_g_ACB0_L, kr_g_ACB0_R,
    kr_g_ACBC_L, kr_g_ACBC_R,
    kr_g_ACBD_L, kr_g_ACBD_R,
    kr_g_ACC4_L, kr_g_ACC4_R,
    kr_g_ACE0_L, kr_g_ACE0_R,
    kr_g_ACF3_L, kr_g_ACF3_R,
    kr_g_ACF5_L, kr_g_ACF5_R,
    kr_g_ACFC_L, kr_g_ACFC_R,
    kr_g_AD00_L, kr_g_AD00_R,
    kr_g_AD11_L, kr_g_AD11_R,
    kr_g_AD34_L, kr_g_AD34_R,
    kr_g_AD6C_L, kr_g_AD6C_R,
    kr_g_AD70_L, kr_g_AD70_R,
    kr_g_AD74_L, kr_g_AD74_R,
    kr_g_ADC4_L, kr_g_ADC4_R,
    kr_g_ADF8_L, kr_g_ADF8_R,
    kr_g_ADFC_L, kr_g_ADFC_R,
    kr_g_AE00_L, kr_g_AE00_R,
    kr_g_AE09_L, kr_g_AE09_R,
    kr_g_AE30_L, kr_g_AE30_R,
    kr_g_AE34_L, kr_g_AE34_R,
    kr_g_AE38_L, kr_g_AE38_R,
    kr_g_AE4A_L, kr_g_AE4A_R,
    kr_g_AE4C_L, kr_g_AE4C_R,
    kr_g_AE4D_L, kr_g_AE4D_R,
    kr_g_AECD_L, kr_g_AECD_R,
    kr_g_AED8_L, kr_g_AED8_R,
    kr_g_AF2D_L, kr_g_AF2D_R,
    kr_g_AF41_L, kr_g_AF41_R,
    kr_g_AF64_L, kr_g_AF64_R,
    kr_g_AFC8_L, kr_g_AFC8_R,
    kr_g_B044_L, kr_g_B044_R,
    kr_g_B053_L, kr_g_B053_R,
    kr_g_B054_L, kr_g_B054_R,
    kr_g_B05D_L, kr_g_B05D_R,
    kr_g_B07C_L, kr_g_B07C_R,
    kr_g_B098_L, kr_g_B098_R,
    kr_g_B099_L, kr_g_B099_R,
    kr_g_B0A0_L, kr_g_B0A0_R,
    kr_g_B0A9_L, kr_g_B0A9_R,
    kr_g_B0B4_L, kr_g_B0B4_R,
    kr_g_B0C9_L, kr_g_B0C9_R,
    kr_g_B0E5_L, kr_g_B0E5_R,
    kr_g_B108_L, kr_g_B108_R,
    kr_g_B10C_L, kr_g_B10C_R,
    kr_g_B110_L, kr_g_B110_R,
    kr_g_B118_L, kr_g_B118_R,
    kr_g_B124_L, kr_g_B124_R,
    kr_g_B140_L, kr_g_B140_R,
    kr_g_B178_L, kr_g_B178_R,
    kr_g_B180_L, kr_g_B180_R,
    kr_g_B192_L, kr_g_B192_R,
    kr_g_B204_L, kr_g_B204_R,
    kr_g_B208_L, kr_g_B208_R,
    kr_g_B20C_L, kr_g_B20C_R,
    kr_g_B294_L, kr_g_B294_R,
    kr_g_B298_L, kr_g_B298_R,
    kr_g_B2C8_L, kr_g_B2C8_R,
    kr_g_B2D8_L, kr_g_B2D8_R,
    kr_g_B2E4_L, kr_g_B2E4_R,
    kr_g_B2E8_L, kr_g_B2E8_R,
    kr_g_B2EC_L, kr_g_B2EC_R,
    kr_g_B2F5_L, kr_g_B2F5_R,
    kr_g_B2F9_L, kr_g_B2F9_R,
    kr_g_B300_L, kr_g_B300_R,
    kr_g_B354_L, kr_g_B354_R,
    kr_g_B355_L, kr_g_B355_R,
    kr_g_B358_L, kr_g_B358_R,
    kr_g_B369_L, kr_g_B369_R,
    kr_g_B370_L, kr_g_B370_R,
    kr_g_B3C4_L, kr_g_B3C4_R,
    kr_g_B3C5_L, kr_g_B3C5_R,
    kr_g_B3CC_L, kr_g_B3CC_R,
    kr_g_B3D9_L, kr_g_B3D9_R,
    kr_g_B3FC_L, kr_g_B3FC_R,
    kr_g_B410_L, kr_g_B410_R,
    kr_g_B418_L, kr_g_B418_R,
    kr_g_B41C_L, kr_g_B41C_R,
    kr_g_B428_L, kr_g_B428_R,
    kr_g_B450_L, kr_g_B450_R,
    kr_g_B458_L, kr_g_B458_R,
    kr_g_B460_L, kr_g_B460_R,
    kr_g_B465_L, kr_g_B465_R,
    kr_g_B46C_L, kr_g_B46C_R,
    kr_g_B4A4_L, kr_g_B4A4_R,
    kr_g_B4DC_L, kr_g_B4DC_R,
    kr_g_B4E0_L, kr_g_B4E0_R,
    kr_g_B4E4_L, kr_g_B4E4_R,
    kr_g_B4EF_L, kr_g_B4EF_R,
    kr_g_B4F1_L, kr_g_B4F1_R,
    kr_g_B514_L, kr_g_B514_R,
    kr_g_B518_L, kr_g_B518_R,
    kr_g_B54C_L, kr_g_B54C_R,
    kr_g_B5A0_L, kr_g_B5A0_R,
    kr_g_B5A8_L, kr_g_B5A8_R,
    kr_g_B69D_L, kr_g_B69D_R,
    kr_g_B6AB_L, kr_g_B6AB_R,
    kr_g_B6F0_L, kr_g_B6F0_R,
    kr_g_B728_L, kr_g_B728_R,
    kr_g_B77C_L, kr_g_B77C_R,
    kr_g_B78C_L, kr_g_B78C_R,
    kr_g_B791_L, kr_g_B791_R,
    kr_g_B798_L, kr_g_B798_R,
    kr_g_B7AD_L, kr_g_B7AD_R,
    kr_g_B7EC_L, kr_g_B7EC_R,
    kr_g_B7FC_L, kr_g_B7FC_R,
    kr_g_B801_L, kr_g_B801_R,
    kr_g_B808_L, kr_g_B808_R,
    kr_g_B824_L, kr_g_B824_R,
    kr_g_B825_L, kr_g_B825_R,
    kr_g_B839_L, kr_g_B839_R,
    kr_g_B85C_L, kr_g_B85C_R,
    kr_g_B85D_L, kr_g_B85D_R,
    kr_g_B8CC_L, kr_g_B8CC_R,
    kr_g_B8E8_L, kr_g_B8E8_R,
    kr_g_B958_L, kr_g_B958_R,
    kr_g_B974_L, kr_g_B974_R,
    kr_g_B978_L, kr_g_B978_R,
    kr_g_B97C_L, kr_g_B97C_R,
    kr_g_B984_L, kr_g_B984_R,
    kr_g_B9AC_L, kr_g_B9AC_R,
    kr_g_B9AD_L, kr_g_B9AD_R,
    kr_g_B9B0_L, kr_g_B9B0_R,
    kr_g_B9BC_L, kr_g_B9BC_R,
    kr_g_B9BF_L, kr_g_B9BF_R,
    kr_g_B9C8_L, kr_g_B9C8_R,
    kr_g_B9C9_L, kr_g_B9C9_R,
    kr_g_B9CC_L, kr_g_B9CC_R,
    kr_g_B9D0_L, kr_g_B9D0_R,
    kr_g_B9DB_L, kr_g_B9DB_R,
    kr_g_B9DE_L, kr_g_B9DE_R,
    kr_g_B9E4_L, kr_g_B9E4_R,
    kr_g_BA38_L, kr_g_BA38_R,
    kr_g_BA3C_L, kr_g_BA3C_R,
    kr_g_BA48_L, kr_g_BA48_R,
    kr_g_BA4D_L, kr_g_BA4D_R,
    kr_g_BA54_L, kr_g_BA54_R,
    kr_g_BA74_L, kr_g_BA74_R,
    kr_g_BA85_L, kr_g_BA85_R,
    kr_g_BAA8_L, kr_g_BAA8_R,
    kr_g_BAA9_L, kr_g_BAA9_R,
    kr_g_BAB8_L, kr_g_BAB8_R,
    kr_g_BABB_L, kr_g_BABB_R,
    kr_g_BB34_L, kr_g_BB34_R,
    kr_g_BB38_L, kr_g_BB38_R,
    kr_g_BB3C_L, kr_g_BB3C_R,
    kr_g_BBF8_L, kr_g_BBF8_R,
    kr_g_BC00_L, kr_g_BC00_R,
    kr_g_BC0D_L, kr_g_BC0D_R,
    kr_g_BC11_L, kr_g_BC11_R,
    kr_g_BC14_L, kr_g_BC14_R,
    kr_g_BC18_L, kr_g_BC18_R,
    kr_g_BC1C_L, kr_g_BC1C_R,
    kr_g_BC1F_L, kr_g_BC1F_R,
    kr_g_BC25_L, kr_g_BC25_R,
    kr_g_BC29_L, kr_g_BC29_R,
    kr_g_BC30_L, kr_g_BC30_R,
    kr_g_BC84_L, kr_g_BC84_R,
    kr_g_BC88_L, kr_g_BC88_R,
    kr_g_BCA0_L, kr_g_BCA0_R,
    kr_g_BCBD_L, kr_g_BCBD_R,
    kr_g_BCC4_L, kr_g_BCC4_R,
    kr_g_BCF4_L, kr_g_BCF4_R,
    kr_g_BCF5_L, kr_g_BCF5_R,
    kr_g_BCFC_L, kr_g_BCFC_R,
    kr_g_BD10_L, kr_g_BD10_R,
    kr_g_BD80_L, kr_g_BD80_R,
    kr_g_BD84_L, kr_g_BD84_R,
    kr_g_BD88_L, kr_g_BD88_R,
    kr_g_BD99_L, kr_g_BD99_R,
    kr_g_BE44_L, kr_g_BE44_R,
    kr_g_BE45_L, kr_g_BE45_R,
    kr_g_BE48_L, kr_g_BE48_R,
    kr_g_BE5B_L, kr_g_BE5B_R,
    kr_g_BE60_L, kr_g_BE60_R,
    kr_g_BE68_L, kr_g_BE68_R,
    kr_g_BED0_L, kr_g_BED0_R,
    kr_g_BF51_L, kr_g_BF51_R,
    kr_g_C0AC_L, kr_g_C0AC_R,
    kr_g_C0AD_L, kr_g_C0AD_R,
    kr_g_C0B0_L, kr_g_C0B0_R,
    kr_g_C0B4_L, kr_g_C0B4_R,
    kr_g_C0BC_L, kr_g_C0BC_R,
    kr_g_C0C1_L, kr_g_C0C1_R,
    kr_g_C0C8_L, kr_g_C0C8_R,
    kr_g_C0DD_L, kr_g_C0DD_R,
    kr_g_C11C_L, kr_g_C11C_R,
    kr_g_C120_L, kr_g_C120_R,
    kr_g_C12C_L, kr_g_C12C_R,
    kr_g_C12F_L, kr_g_C12F_R,
    kr_g_C131_L, kr_g_C131_R,
    kr_g_C138_L, kr_g_C138_R,
    kr_g_C18D_L, kr_g_C18D_R,
    kr_g_C190_L, kr_g_C190_R,
    kr_g_C1E0_L, kr_g_C1E0_R,
    kr_g_C218_L, kr_g_C218_R,
    kr_g_C228_L, kr_g_C228_R,
    kr_g_C22D_L, kr_g_C22D_R,
    kr_g_C234_L, kr_g_C234_R,
    kr_g_C2A4_L, kr_g_C2A4_R,
    kr_g_C2AC_L, kr_g_C2AC_R,
    kr_g_C2AD_L, kr_g_C2AD_R,
    kr_g_C2B5_L, kr_g_C2B5_R,
    kr_g_C2B9_L, kr_g_C2B9_R,
    kr_g_C2DC_L, kr_g_C2DC_R,
    kr_g_C2E0_L, kr_g_C2E0_R,
    kr_g_C2E4_L, kr_g_C2E4_R,
    kr_g_C2EC_L, kr_g_C2EC_R,
    kr_g_C2F6_L, kr_g_C2F6_R,
    kr_g_C2F8_L, kr_g_C2F8_R,
    kr_g_C2FC_L, kr_g_C2FC_R,
    kr_g_C313_L, kr_g_C313_R,
    kr_g_C368_L, kr_g_C368_R,
    kr_g_C370_L, kr_g_C370_R,
    kr_g_C384_L, kr_g_C384_R,
    kr_g_C544_L, kr_g_C544_R,
    kr_g_C548_L, kr_g_C548_R,
    kr_g_C549_L, kr_g_C549_R,
    kr_g_C54A_L, kr_g_C54A_R,
    kr_g_C554_L, kr_g_C554_R,
    kr_g_C558_L, kr_g_C558_R,
    kr_g_C55E_L, kr_g_C55E_R,
    kr_g_C57C_L, kr_g_C57C_R,
    kr_g_C595_L, kr_g_C595_R,
    kr_g_C5B4_L, kr_g_C5B4_R,
    kr_g_C5B8_L, kr_g_C5B8_R,
    kr_g_C5BC_L, kr_g_C5BC_R,
    kr_g_C5C4_L, kr_g_C5C4_R,
    kr_g_C5C6_L, kr_g_C5C6_R,
    kr_g_C5D0_L, kr_g_C5D0_R,
    kr_g_C5D8_L, kr_g_C5D8_R,
    kr_g_C5EC_L, kr_g_C5EC_R,
    kr_g_C5F0_L, kr_g_C5F0_R,
    kr_g_C5F4_L, kr_g_C5F4_R,
    kr_g_C608_L, kr_g_C608_R,
    kr_g_C624_L, kr_g_C624_R,
    kr_g_C62C_L, kr_g_C62C_R,
    kr_g_C634_L, kr_g_C634_R,
    kr_g_C640_L, kr_g_C640_R,
    kr_g_C644_L, kr_g_C644_R,
    kr_g_C654_L, kr_g_C654_R,
    kr_g_C678_L, kr_g_C678_R,
    kr_g_C67C_L, kr_g_C67C_R,
    kr_g_C694_L, kr_g_C694_R,
    kr_g_C6A9_L, kr_g_C6A9_R,
    kr_g_C6B0_L, kr_g_C6B0_R,
    kr_g_C6B4_L, kr_g_C6B4_R,
    kr_g_C6C0_L, kr_g_C6C0_R,
    kr_g_C6CC_L, kr_g_C6CC_R,
    kr_g_C6D0_L, kr_g_C6D0_R,
    kr_g_C6DC_L, kr_g_C6DC_R,
    kr_g_C704_L, kr_g_C704_R,
    kr_g_C720_L, kr_g_C720_R,
    kr_g_C73C_L, kr_g_C73C_R,
    kr_g_C740_L, kr_g_C740_R,
    kr_g_C744_L, kr_g_C744_R,
    kr_g_C74C_L, kr_g_C74C_R,
    kr_g_C758_L, kr_g_C758_R,
    kr_g_C774_L, kr_g_C774_R,
    kr_g_C778_L, kr_g_C778_R,
    kr_g_C77C_L, kr_g_C77C_R,
    kr_g_C77D_L, kr_g_C77D_R,
    kr_g_C783_L, kr_g_C783_R,
    kr_g_C784_L, kr_g_C784_R,
    kr_g_C788_L, kr_g_C788_R,
    kr_g_C790_L, kr_g_C790_R,
    kr_g_C791_L, kr_g_C791_R,
    kr_g_C796_L, kr_g_C796_R,
    kr_g_C798_L, kr_g_C798_R,
    kr_g_C7A0_L, kr_g_C7A0_R,
    kr_g_C7A1_L, kr_g_C7A1_R,
    kr_g_C7A5_L, kr_g_C7A5_R,
    kr_g_C7AC_L, kr_g_C7AC_R,
    kr_g_C7BD_L, kr_g_C7BD_R,
    kr_g_C7C1_L, kr_g_C7C1_R,
    kr_g_C800_L, kr_g_C800_R,
    kr_g_C801_L, kr_g_C801_R,
    kr_g_C804_L, kr_g_C804_R,
    kr_g_C808_L, kr_g_C808_R,
    kr_g_C810_L, kr_g_C810_R,
    kr_g_C815_L, kr_g_C815_R,
    kr_g_C81C_L, kr_g_C81C_R,
    kr_g_C838_L, kr_g_C838_R,
    kr_g_C870_L, kr_g_C870_R,
    kr_g_C871_L, kr_g_C871_R,
    kr_g_C878_L, kr_g_C878_R,
    kr_g_C885_L, kr_g_C885_R,
    kr_g_C88B_L, kr_g_C88B_R,
    kr_g_C8FC_L, kr_g_C8FC_R,
    kr_g_C900_L, kr_g_C900_R,
    kr_g_C904_L, kr_g_C904_R,
    kr_g_C911_L, kr_g_C911_R,
    kr_g_C918_L, kr_g_C918_R,
    kr_g_C950_L, kr_g_C950_R,
    kr_g_C990_L, kr_g_C990_R,
    kr_g_C9C0_L, kr_g_C9C0_R,
    kr_g_C9C1_L, kr_g_C9C1_R,
    kr_g_C9C4_L, kr_g_C9C4_R,
    kr_g_C9C8_L, kr_g_C9C8_R,
    kr_g_C9D1_L, kr_g_C9D1_R,
    kr_g_C9DC_L, kr_g_C9DC_R,
    kr_g_C9F8_L, kr_g_C9F8_R,
    kr_g_CABD_L, kr_g_CABD_R,
    kr_g_CC0C_L, kr_g_CC0C_R,
    kr_g_CC28_L, kr_g_CC28_R,
    kr_g_CC2C_L, kr_g_CC2C_R,
    kr_g_CC3E_L, kr_g_CC3E_R,
    kr_g_CC45_L, kr_g_CC45_R,
    kr_g_CC98_L, kr_g_CC98_R,
    kr_g_CCD0_L, kr_g_CCD0_R,
    kr_g_CD08_L, kr_g_CD08_R,
    kr_g_CD5C_L, kr_g_CD5C_R,
    kr_g_CD95_L, kr_g_CD95_R,
    kr_g_CD9C_L, kr_g_CD9C_R,
    kr_g_CDA9_L, kr_g_CDA9_R,
    kr_g_CDB0_L, kr_g_CDB0_R,
    kr_g_CE58_L, kr_g_CE58_R,
    kr_g_CE5C_L, kr_g_CE5C_R,
    kr_g_CE74_L, kr_g_CE74_R,
    kr_g_CE90_L, kr_g_CE90_R,
    kr_g_CF00_L, kr_g_CF00_R,
    kr_g_CF54_L, kr_g_CF54_R,
    kr_g_CFE0_L, kr_g_CFE0_R,
    kr_g_CFE8_L, kr_g_CFE8_R,
    kr_g_D06C_L, kr_g_D06C_R,
    kr_g_D070_L, kr_g_D070_R,
    kr_g_D074_L, kr_g_D074_R,
    kr_g_D07C_L, kr_g_D07C_R,
    kr_g_D0A4_L, kr_g_D0A4_R,
    kr_g_D0B9_L, kr_g_D0B9_R,
    kr_g_D0C0_L, kr_g_D0C0_R,
    kr_g_D0C4_L, kr_g_D0C4_R,
    kr_g_D0C8_L, kr_g_D0C8_R,
    kr_g_D0D1_L, kr_g_D0D1_R,
    kr_g_D0DD_L, kr_g_D0DD_R,
    kr_g_D130_L, kr_g_D130_R,
    kr_g_D14C_L, kr_g_D14C_R,
    kr_g_D1A4_L, kr_g_D1A4_R,
    kr_g_D1B1_L, kr_g_D1B1_R,
    kr_g_D1B5_L, kr_g_D1B5_R,
    kr_g_D22C_L, kr_g_D22C_R,
    kr_g_D2B8_L, kr_g_D2B8_R,
    kr_g_D2B9_L, kr_g_D2B9_R,
    kr_g_D2BC_L, kr_g_D2BC_R,
    kr_g_D2C0_L, kr_g_D2C0_R,
    kr_g_D2C8_L, kr_g_D2C8_R,
    kr_g_D2F4_L, kr_g_D2F4_R,
    kr_g_D30C_L, kr_g_D30C_R,
    kr_g_D310_L, kr_g_D310_R,
    kr_g_D37C_L, kr_g_D37C_R,
    kr_g_D3AD_L, kr_g_D3AD_R,
    kr_g_D3B8_L, kr_g_D3B8_R,
    kr_g_D3C9_L, kr_g_D3C9_R,
    kr_g_D3EC_L, kr_g_D3EC_R,
    kr_g_D3ED_L, kr_g_D3ED_R,
    kr_g_D3F0_L, kr_g_D3F0_R,
    kr_g_D45C_L, kr_g_D45C_R,
    kr_g_D478_L, kr_g_D478_R,
    kr_g_D504_L, kr_g_D504_R,
    kr_g_D50C_L, kr_g_D50C_R,
    kr_g_D53C_L, kr_g_D53C_R,
    kr_g_D558_L, kr_g_D558_R,
    kr_g_D55C_L, kr_g_D55C_R,
    kr_g_D560_L, kr_g_D560_R,
    kr_g_D568_L, kr_g_D568_R,
    kr_g_D569_L, kr_g_D569_R,
    kr_g_D56D_L, kr_g_D56D_R,
    kr_g_D574_L, kr_g_D574_R,
    kr_g_D589_L, kr_g_D589_R,
    kr_g_D5D8_L, kr_g_D5D8_R,
    kr_g_D5E4_L, kr_g_D5E4_R,
    kr_g_D615_L, kr_g_D615_R,
    kr_g_D654_L, kr_g_D654_R,
    kr_g_D655_L, kr_g_D655_R,
    kr_g_D68C_L, kr_g_D68C_R,
    kr_g_D6D4_L, kr_g_D6D4_R,
    kr_g_D754_L, kr_g_D754_R,
    kr_g_D788_L, kr_g_D788_R,
    kr_g_D78C_L, kr_g_D78C_R,
    kr_g_D798_L, kr_g_D798_R,
};
