#!/usr/bin/env python3
# 한국어 텍스트 파이프라인 (단일 소스). 아래 SRC_GLOBS 의 소스 파일들을 스캔해:
#   (1) 유니크 한글 음절 수집 → 코드포인트 정렬로 안정 인덱스 부여
#   (2) 음절별 8x16 반쪽 글리프 2개(IA4, PF스타더스트 S 확정규격) → textures/segment2/kr/
#   (3) kr_glyphs[] LUT (.inc.c)  — bin/segment2.c 가 include
#   (4) charmap_kr.txt = 기존 charmap.txt + 음절→{0xFB, hi, lo}
#
# 인코딩: 한글 음절 = { KR_ESC(0xFB), idx_hi, idx_lo }.  textconv 가 charmap_kr.txt 로
# 대사/코스/메뉴 문자열(_("...") )을 자동 한글 인코딩한다. 렌더러(ingame_menu.c)가
# KR_ESC 를 만나면 kr_glyphs[idx*2], [idx*2+1] (좌/우 반쪽)을 8px 씩 그린다.
#
# 사용: tools/kr_gen.py   (Pillow 필요. 번역 텍스트 추가/수정 후 재실행 → 전부 자동 갱신)
import os, subprocess, glob
from PIL import Image, ImageFont, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(ROOT, "tools", "pf_stardust_s.ttf")
N64G = os.path.join(ROOT, "tools", "n64graphics")
GLYPH_DIR = os.path.join(ROOT, "textures", "segment2", "kr")
KR_ESC = 0xFB

# 한글이 들어갈 수 있는 소스 파일들 (여기서 음절 수집)
SRC_GLOBS = [
    os.path.join(ROOT, "text", "kr", "*.h"),
    os.path.join(ROOT, "include", "text_strings.kr.h.in"),
]

# 확정 렌더 규격 (바꾸지 말 것 — mario-korean-handoff.md §3)
FSIZE, TOP = 19, 2
R270 = Image.Transpose.ROTATE_270
FL = Image.Transpose.FLIP_LEFT_RIGHT

def is_hangul(c):
    return 0xAC00 <= ord(c) <= 0xD7A3

def collect_syllables():
    seen = set()
    for pat in SRC_GLOBS:
        for path in glob.glob(pat):
            with open(path, encoding="utf-8") as f:
                for c in f.read():
                    if is_hangul(c):
                        seen.add(c)
    return sorted(seen)  # 코드포인트 정렬 → 결정적/안정 인덱스

def render_half_pngs(ch, font):
    g = Image.new("L", (16, 16), 0)
    d = ImageDraw.Draw(g)
    bb = d.textbbox((0, 0), ch, font=font)
    w = bb[2] - bb[0]
    if w > 16:
        print("  ⚠ '%s' 폭 %d>16" % (ch, w))
    d.text(((16 - w) // 2 - bb[0], -bb[1] + TOP), ch, fill=255, font=font)
    m = g.point(lambda v: 255 if v >= 128 else 0)  # 하드 임계값 (AA 회색 제거)
    la = Image.merge("LA", (m, m))
    out = {}
    for half, x0 in (("L", 0), ("R", 8)):
        out[half] = la.crop((x0, 0, x0 + 8, 16)).transpose(FL).transpose(R270)  # 저장 방향
    return out

def main():
    os.makedirs(GLYPH_DIR, exist_ok=True)
    font = ImageFont.truetype(FONT, FSIZE)
    syllables = collect_syllables()
    print("유니크 음절 %d개" % len(syllables))
    if not syllables:
        print("  (한글 소스 없음 — text/kr/*.h, text_strings.kr.h.in 확인)")

    # (2) 글리프 생성 (이미 있으면 스킵 → 증분 번역 빠름. 글리프는 인덱스 무관)
    made, cached = 0, 0
    for ch in syllables:
        code = "%04X" % ord(ch)
        need = [h for h in ("L", "R")
                if not os.path.exists(os.path.join(GLYPH_DIR, "kr_%s_%s.ia4.inc.c" % (code, h)))]
        if not need:
            cached += 1
            continue
        pngs = render_half_pngs(ch, font)
        for half in need:
            png = os.path.join(GLYPH_DIR, "kr_%s_%s.png" % (code, half))
            inc = os.path.join(GLYPH_DIR, "kr_%s_%s.ia4.inc.c" % (code, half))
            pngs[half].save(png)
            subprocess.run([N64G, "-s", "u8", "-i", inc, "-g", png, "-f", "ia4"], check=True)
            os.remove(png)
        made += 1
    print("글리프: 신규 %d, 캐시 %d" % (made, cached))

    # (3) kr_glyphs.inc.c (텍스처 defs + 배열, 정렬순 인덱스)
    with open(os.path.join(GLYPH_DIR, "kr_glyphs.inc.c"), "w") as f:
        f.write("// auto-generated by tools/kr_gen.py — 한글 반쪽 글리프 테이블 (음절*2 + 0/1 = 좌/우)\n")
        for ch in syllables:
            code = "%04X" % ord(ch)
            for half in ("L", "R"):
                f.write('ALIGNED8 static const Texture kr_g_%s_%s[] = {\n'
                        '#include "textures/segment2/kr/kr_%s_%s.ia4.inc.c"\n};\n'
                        % (code, half, code, half))
        f.write("\nconst Texture *const kr_glyphs[] = {\n")
        for ch in syllables:
            code = "%04X" % ord(ch)
            f.write("    kr_g_%s_L, kr_g_%s_R,\n" % (code, code))
        f.write("};\n")

    # (4) charmap_kr.txt = charmap.txt (ASCII/기호/특수문자 전부) + 한글 음절
    with open(os.path.join(ROOT, "charmap.txt"), encoding="utf-8") as f:
        base = f.read()
    with open(os.path.join(ROOT, "charmap_kr.txt"), "w", encoding="utf-8") as f:
        f.write(base)
        if not base.endswith("\n"):
            f.write("\n")
        f.write("\n# ── 한글 음절 (auto-generated by tools/kr_gen.py) → { 0xFB, idx_hi, idx_lo } ──\n")
        for i, ch in enumerate(syllables):
            f.write("'%s' = 0x%02X, 0x%02X, 0x%02X\n" % (ch, KR_ESC, (i >> 8) & 0xFF, i & 0xFF))

    print("생성: kr_glyphs.inc.c, charmap_kr.txt (%d 음절)" % len(syllables))

main()
